name: Build and Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get -y install dos2unix

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: |
          chmod +x gradlew
          dos2unix ./gradlew
          ./gradlew assemble

      - name: apk
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk
